import type { Metadata } from "next";
import { ChakraProvider } from "@chakra-ui/react";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/app/authContext";

export const metadata: Metadata = {
  title: "Carefinder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
        <ChakraProvider>
        <div className="flex flex-col justify-between min-h-[100vh]">
          <div>
          <Navbar />
          <div className="mt-[3%]">
          {children}
          </div>
          </div>
          <Footer />
          </div>
          </ChakraProvider>
          </AuthProvider>
      </body>
    </html>
  );
}
